-- Great Diplomat names
INSERT INTO Language_ko_KR
	(Tag, Text, Plurality)
VALUES
	('TXT_KEY_GREAT_PERSON_KISSINGER', '헨리 키신저', 2),
	('TXT_KEY_GREAT_PERSON_ALBRIGHT', '매들린 올브라이트', 2),
	('TXT_KEY_GREAT_PERSON_ANNAN', '코피 아난', 1),
	('TXT_KEY_GREAT_PERSON_BAN', '반기문', 1),
	('TXT_KEY_GREAT_PERSON_BELL', '거트루드 벨', 1),
	('TXT_KEY_GREAT_PERSON_DAG', '다그 함마르셸드', 2),
	('TXT_KEY_GREAT_PERSON_DINTEVILLE', '장 드 댕트빌', 1),
	('TXT_KEY_GREAT_PERSON_DURRELL', '로렌스 더럴', 1),
	('TXT_KEY_GREAT_PERSON_JAY', '존 제이', 2),
	('TXT_KEY_GREAT_PERSON_KOLLONTAI', '알렉산드라 콜론타이', 2),
	('TXT_KEY_GREAT_PERSON_LAWRENCE', '토머스 에드워드 로렌스', 2),
	('TXT_KEY_GREAT_PERSON_METTERNICH', '클레멘스 폰 메테르니히', 2),
	('TXT_KEY_GREAT_PERSON_NERUDA', '파블로 네루다', 2),
	('TXT_KEY_GREAT_PERSON_ODO', '오도 러셀', 1),
	('TXT_KEY_GREAT_PERSON_SELVE', '조지 드 셀브', 2),
	('TXT_KEY_GREAT_PERSON_SEWARD', '윌리엄 H. 수어드', 2),
	('TXT_KEY_GREAT_PERSON_SHIGERU', '요시다 시게루', 2),
	('TXT_KEY_GREAT_PERSON_SZABO', '바이올렛 스자보', 2),
	('TXT_KEY_GREAT_PERSON_TALLEYRAND', '샤를모리스 드 탈레랑페리고르', 2),
	('TXT_KEY_GREAT_PERSON_THANT', '우 탄트', 2),
	('TXT_KEY_GREAT_PERSON_WALDHEIM', '쿠르트 발트하임', 1),
	('TXT_KEY_GREAT_PERSON_WALLENBERG', '라울 발렌베리', 2),
	('TXT_KEY_GREAT_PERSON_WEIJUN', '구웨이쥔', 1),
	('TXT_KEY_GREAT_PERSON_WHOWARD', '윌리암 하워드', 2),
	('TXT_KEY_GREAT_PERSON_ZIMMERMAN', '짐머만', 1),
	('TXT_KEY_GREAT_PERSON_D__010', '하투실리스 3세', 2),
	('TXT_KEY_GREAT_PERSON_D__020', '티투스 퀸크티우스 플라미니우스', 2),
	('TXT_KEY_GREAT_PERSON_D__025', '장건', 1),
	('TXT_KEY_GREAT_PERSON_D__030', '교황 레오 1세', 2),
	('TXT_KEY_GREAT_PERSON_D__035', '왕현책', 1),
	('TXT_KEY_GREAT_PERSON_D__040', '지곤사시', 2),
	('TXT_KEY_GREAT_PERSON_D__050', '카스틸리오네', 2),
	('TXT_KEY_GREAT_PERSON_D__060', '유스티스 차퍼이즈', 2),
	('TXT_KEY_GREAT_PERSON_D__070', '카메하메하 3세', 2),
	('TXT_KEY_GREAT_PERSON_D__080', '파르갈리 이브라힘 파사', 2),
	('TXT_KEY_GREAT_PERSON_D__090', '토머스 로 경', 1),
	('TXT_KEY_GREAT_PERSON_D__100', '휴고 그로티우스', 2),
	('TXT_KEY_GREAT_PERSON_D__110', '요한 루돌프 베츠슈타인', 1),
	('TXT_KEY_GREAT_PERSON_D__120', '코사 판', 1),
	('TXT_KEY_GREAT_PERSON_D__130', '조지 매카트니', 2),
	('TXT_KEY_GREAT_PERSON_D__140', '모슈슈 1세', 2),
	('TXT_KEY_GREAT_PERSON_D__150', '스트랫포드 캐닝 경', 1),
	('TXT_KEY_GREAT_PERSON_D__160', '알버트 멘스도르프', 2),
	('TXT_KEY_GREAT_PERSON_D__170', '호세 마리아 다 실바 파라노스', 2),
	('TXT_KEY_GREAT_PERSON_D__180', '오레스테스 페라라', 2),
	('TXT_KEY_GREAT_PERSON_D__190', '사무엘 에벤느저 룽간단 경', 1),
	('TXT_KEY_GREAT_PERSON_D__200', '로버트 이든', 1),
	('TXT_KEY_GREAT_PERSON_D__210', '트란 반 추옹', 1),
	('TXT_KEY_GREAT_PERSON_D__220', '미겔 앙헬 아스투리아스', 2),
	('TXT_KEY_GREAT_PERSON_D__230', '나르시소 라모스', 2),	
	('TXT_KEY_GREAT_PERSON_D__240', '수잔 보렐', 1),
	('TXT_KEY_GREAT_PERSON_D__250', '조지 캐넌', 1),
	('TXT_KEY_GREAT_PERSON_D__260', '야코프 말리크', 2),
	('TXT_KEY_GREAT_PERSON_D__270', '샹커 샴셔 장 바하두르 라나', 2),
	('TXT_KEY_GREAT_PERSON_D__280', '아담 말릭', 1),
	('TXT_KEY_GREAT_PERSON_D__290', '스테판 헤셀', 1),
	('TXT_KEY_GREAT_PERSON_D__300', '하비에르 페레스 데 케야르', 2),
	('TXT_KEY_GREAT_PERSON_D__310', '부트로스 부트로스 갈리', 2),
	('TXT_KEY_GREAT_PERSON_D__320', '맥스 제이콥슨', 1),
	('TXT_KEY_GREAT_PERSON_D__330', '제라드 오우에드라고', 2),
	('TXT_KEY_GREAT_PERSON_D__340', '예두아르트 셰바르드나제', 2),
	('TXT_KEY_GREAT_PERSON_D__350', '즈비그뉴 브레진스키', 2),
	('TXT_KEY_GREAT_PERSON_D__360', '로렌스 이글버거', 2),
	('TXT_KEY_GREAT_PERSON_D__370', '레드하 말렉', 1),	
	('TXT_KEY_GREAT_PERSON_D__380', '파트릭 노통브', 2),
	('TXT_KEY_GREAT_PERSON_D__390', '라비 메사리', 2),
	('TXT_KEY_GREAT_PERSON_D__400', '도널드 맥헨리', 2),
	('TXT_KEY_GREAT_PERSON_D__410', '피터 제이', 2),
	('TXT_KEY_GREAT_PERSON_D__420', '알리 트레키', 2),
	('TXT_KEY_GREAT_PERSON_D__430', '마르티 아티사리', 2),
	('TXT_KEY_GREAT_PERSON_D__440', '자크 디우프', 2),
	('TXT_KEY_GREAT_PERSON_D__450', '지리 그루사', 2),
	('TXT_KEY_GREAT_PERSON_D__460', '엔디미온 윌킨슨', 1),
	('TXT_KEY_GREAT_PERSON_D__470', '마운트가 디알로', 2),
	('TXT_KEY_GREAT_PERSON_D__480', '미고네트 패트리샤 듀란트', 2),
	('TXT_KEY_GREAT_PERSON_D__490', '아서 J. 콜링스워스', 2),
	('TXT_KEY_GREAT_PERSON_D__500', '로우벌 오울헤이', 2),
	('TXT_KEY_GREAT_PERSON_D__510', '세자르 마요랄', 1),
	('TXT_KEY_GREAT_PERSON_D__520', '무토 마사토시', 2),
	('TXT_KEY_GREAT_PERSON_D__530', '베네딕트 아스게이르손', 1),
	('TXT_KEY_GREAT_PERSON_D__540', '후안 마누엘 산토스', 2),
	('TXT_KEY_GREAT_PERSON_D__550', '비탈리 츄르킨', 1),
	('TXT_KEY_GREAT_PERSON_D__560', '안드레이 카를로프', 2),
	('TXT_KEY_GREAT_PERSON_D__570', '매트 로비', 2),
	('TXT_KEY_GREAT_PERSON_D__580', '사엡 에라카트', 2),
	('TXT_KEY_GREAT_PERSON_D__590', '자말 카쇼기', 2),
	('TXT_KEY_GREAT_PERSON_D__600', '자오리젠', 1),
	('TXT_KEY_GREAT_PERSON_D__610', '레이첼 오마모', 2),
	('TXT_KEY_GREAT_PERSON_D__620', '수잔 라이스', 2),
	('TXT_KEY_GREAT_PERSON_D__630', '아메드 사리르', 2),
	('TXT_KEY_GREAT_PERSON_D__640', '사만다 스미스', 2),
	('TXT_KEY_GREAT_PERSON_D__650', '니콜라 디미트로프', 2),
	('TXT_KEY_GREAT_PERSON_D__660', '캐롤린 로드리게스', 2),
	('TXT_KEY_GREAT_PERSON_D__670', '부크 예레미치', 2),
	('TXT_KEY_GREAT_PERSON_D__680', '아비 아머드 알리', 2),
	('TXT_KEY_GREAT_PERSON_D__690', '줄리 샤펠', 1),
	('TXT_KEY_GREAT_PERSON_D__700', '나디아 무라드', 2),
	('TXT_KEY_GREAT_PERSON_D__710', '말랄라 유사프자이', 2),
	('TXT_KEY_GREAT_PERSON_D__720', '템플 이스트몬드', 2),
	('TXT_KEY_GREAT_PERSON_D__730', '그레타 툰베리', 2);
