--  MoreGPs - Extra Great Peoples for VP - Version b3 rev 5
--	(GREAT DIPLOMATES part)

-- --------------------------------------------------------------------------------
--
--          G.DIPLOMATES
--
-- --------------------------------------------------------------------------------

INSERT INTO Language_ko_KR
	(Tag, Text)
VALUES
	('TXT_KEY_GREAT_PERSON_D__010', '하투실리스 3세'),
	('TXT_KEY_GREAT_PERSON_D__020', '티투스 퀸크티우스 플라미니우스'),
	('TXT_KEY_GREAT_PERSON_D__025', '장건'),
	('TXT_KEY_GREAT_PERSON_D__030', '교황 레오 1세'),
	('TXT_KEY_GREAT_PERSON_D__035', '왕현책'),
	('TXT_KEY_GREAT_PERSON_D__040', '지곤사시'),
	('TXT_KEY_GREAT_PERSON_D__050', '카스틸리오네'),
	('TXT_KEY_GREAT_PERSON_D__060', '유스티스 차퍼이즈'),
	('TXT_KEY_GREAT_PERSON_D__070', '카메하메하 3세'),
	('TXT_KEY_GREAT_PERSON_D__080', '파르갈리 이브라힘 파사'),
	('TXT_KEY_GREAT_PERSON_D__090', '토머스 로 경'),
	('TXT_KEY_GREAT_PERSON_D__100', '휴고 그로티우스'),
	('TXT_KEY_GREAT_PERSON_D__110', '요한 루돌프 베츠슈타인'),
	('TXT_KEY_GREAT_PERSON_D__120', '코사 판'),
	('TXT_KEY_GREAT_PERSON_D__130', '조지 매카트니'),
	('TXT_KEY_GREAT_PERSON_D__140', '모슈슈 1세'),
	('TXT_KEY_GREAT_PERSON_D__150', '스트랫포드 캐닝 경'),
	('TXT_KEY_GREAT_PERSON_D__160', '알버트 멘스도르프'),
	('TXT_KEY_GREAT_PERSON_D__170', '호세 마리아 다 실바 파라노스'),
	('TXT_KEY_GREAT_PERSON_D__180', '오레스테스 페라라'),
	('TXT_KEY_GREAT_PERSON_D__190', '사무엘 에벤느저 룽간단 경'),
	('TXT_KEY_GREAT_PERSON_D__200', '로버트 이든'),
	('TXT_KEY_GREAT_PERSON_D__210', '트란 반 추옹'),
	('TXT_KEY_GREAT_PERSON_D__220', '미겔 앙헬 아스투리아스'),
	('TXT_KEY_GREAT_PERSON_D__230', '나르시소 라모스'),	
	('TXT_KEY_GREAT_PERSON_D__240', '수잔 보렐'),
	('TXT_KEY_GREAT_PERSON_D__250', '조지 캐넌'),
	('TXT_KEY_GREAT_PERSON_D__260', '야코프 말리크'),
	('TXT_KEY_GREAT_PERSON_D__270', '샹커 샴셔 장 바하두르 라나'),
	('TXT_KEY_GREAT_PERSON_D__280', '아담 말릭'),
	('TXT_KEY_GREAT_PERSON_D__290', '스테판 헤셀'),
	('TXT_KEY_GREAT_PERSON_D__300', '하비에르 페레스 데 케야르'),
	('TXT_KEY_GREAT_PERSON_D__310', '부트로스 부트로스 갈리'),
	('TXT_KEY_GREAT_PERSON_D__320', '맥스 제이콥슨'),
	('TXT_KEY_GREAT_PERSON_D__330', '제라드 오우에드라고'),
	('TXT_KEY_GREAT_PERSON_D__340', '예두아르트 셰바르드나제'),
	('TXT_KEY_GREAT_PERSON_D__350', '즈비그뉴 브레진스키'),
	('TXT_KEY_GREAT_PERSON_D__360', '로렌스 이글버거'),
	('TXT_KEY_GREAT_PERSON_D__370', '레드하 말렉'),	
	('TXT_KEY_GREAT_PERSON_D__380', '파트릭 노통브'),
	('TXT_KEY_GREAT_PERSON_D__390', '라비 메사리'),
	('TXT_KEY_GREAT_PERSON_D__400', '도널드 맥헨리'),
	('TXT_KEY_GREAT_PERSON_D__410', '피터 제이'),
	('TXT_KEY_GREAT_PERSON_D__420', '알리 트레키'),
	('TXT_KEY_GREAT_PERSON_D__430', '마르티 아티사리'),
	('TXT_KEY_GREAT_PERSON_D__440', '자크 디우프'),
	('TXT_KEY_GREAT_PERSON_D__450', '지리 그루사'),
	('TXT_KEY_GREAT_PERSON_D__460', '엔디미온 윌킨슨'),
	('TXT_KEY_GREAT_PERSON_D__470', '마운트가 디알로'),
	('TXT_KEY_GREAT_PERSON_D__480', '미고네트 패트리샤 듀란트'),
	('TXT_KEY_GREAT_PERSON_D__490', '아서 J. 콜링스워스'),
	('TXT_KEY_GREAT_PERSON_D__500', '로우벌 오울헤이'),
	('TXT_KEY_GREAT_PERSON_D__510', '세자르 마요랄'),
	('TXT_KEY_GREAT_PERSON_D__520', '무토 마사토시'),
	('TXT_KEY_GREAT_PERSON_D__530', '베네딕트 아스게이르손'),
	('TXT_KEY_GREAT_PERSON_D__540', '후안 마누엘 산토스'),
	('TXT_KEY_GREAT_PERSON_D__550', '비탈리 츄르킨'),
	('TXT_KEY_GREAT_PERSON_D__560', '안드레이 카를로프'),
	('TXT_KEY_GREAT_PERSON_D__570', '매트 로비'),
	('TXT_KEY_GREAT_PERSON_D__580', '사엡 에라카트'),
	('TXT_KEY_GREAT_PERSON_D__590', '자말 카쇼기'),
	('TXT_KEY_GREAT_PERSON_D__600', '자오리젠'),
	('TXT_KEY_GREAT_PERSON_D__610', '레이첼 오마모'),
	('TXT_KEY_GREAT_PERSON_D__620', '수잔 라이스'),
	('TXT_KEY_GREAT_PERSON_D__630', '아메드 사리르'),
	('TXT_KEY_GREAT_PERSON_D__640', '사만다 스미스'),
	('TXT_KEY_GREAT_PERSON_D__650', '니콜라 디미트로프'),
	('TXT_KEY_GREAT_PERSON_D__660', '캐롤린 로드리게스'),
	('TXT_KEY_GREAT_PERSON_D__670', '부크 예레미치'),
	('TXT_KEY_GREAT_PERSON_D__680', '아비 아머드 알리'),
	('TXT_KEY_GREAT_PERSON_D__690', '줄리 샤펠'),
	('TXT_KEY_GREAT_PERSON_D__700', '나디아 무라드'),
	('TXT_KEY_GREAT_PERSON_D__710', '말랄라 유사프자이'),
	('TXT_KEY_GREAT_PERSON_D__720', '템플 이스트몬드'),
	('TXT_KEY_GREAT_PERSON_D__730', '그레타 툰베리');
