-- Hovering Unit
UPDATE Language_ko_KR
SET Text = '산 타일 상공 통과 가능, 승선 없이 물 타일 통과 가능. 해양 타일에서 [COLOR_NEGATIVE_TEXT]공격 불가[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_HOVERING_UNIT_HELP';

-- Withdraw Before Melee
UPDATE Language_ko_KR
SET Text = '유닛 뒤에 공간이 있다면 매 턴 첫 근접 공격을 피해 후퇴'
WHERE Tag = 'TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_HELP';

-- Himeji Castle
UPDATE Language_ko_KR
SET Text = '우호 영토 내 전투 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP';

UPDATE Language_ko_KR
SET Text = '마크스맨쉽'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED';

UPDATE Language_ko_KR
SET Text = '부상 유닛 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP';

-- Great General Combat Bonus
UPDATE Language_ko_KR
SET Text = '위대한 장군과 같은 타일에서 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_GENERAL_STACKING_HELP';

-- Statue Of Zeus
UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]군사 유닛:[ENDCOLOR] 도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR][NEWLINE][COLOR_POSITIVE_TEXT]노동자:[ENDCOLOR] 전쟁 포로의 작업 속도 감소 면역'
WHERE Tag = 'TXT_KEY_PROMOTION_STATUE_ZEUS_HELP';

-- Mobility, Mobility I, Mobility II
UPDATE Language_ko_KR
SET Text = '[ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_HELP';

-- Scouting
UPDATE Language_ko_KR
SET Text = '[ICON_VP_VISION] 시야 +1'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_VP_VISION] 시야 +1'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_3_HELP';

-- Sentry
UPDATE Language_ko_KR
SET Text = '[ICON_VP_VISION] 시야 +1'
WHERE Tag = 'TXT_KEY_PROMOTION_SENTRY_HELP';

-- Enhanced Flank Attack
UPDATE Language_ko_KR
SET Text = '측면 공격 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP';

-- Combat Bonus in Forest/Jungle (33)
UPDATE Language_ko_KR
SET Text = '숲 및 정글에서 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MOHAWK_HELP';

-- Combat Bonus in Forest/Jungle (33)
UPDATE Language_ko_KR
SET Text = '숲 및 정글에서 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_JAGUAR_HELP';

UPDATE Language_ko_KR
SET Text = '하이랜더'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY';

UPDATE Language_ko_KR
SET Text = '설원, 툰드라, 언덕 타일에서 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR][NEWLINE][COLOR:110:110:110:255](숲 또는 정글 존재 시 보너스 없음)[ENDCOLOR][NEWLINE]설원, 툰드라, 언덕 타일에서 [ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]두 배[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY_HELP';

UPDATE Language_ko_KR
SET Text = '원정 전쟁'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]우호 영토 밖[ENDCOLOR]에서 전투시 +20% [ICON_STRENGTH] 전투력.'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS_HELP';

-- Homeland Guardian
UPDATE Language_ko_KR
SET Text = '우호 영토 내 전투 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_HOMELAND_GUARDIAN_HELP';

-- Full Moon Striker
UPDATE Language_ko_KR
SET Text = '[ICON_MOVES] 헹동력 +1.[NEWLINE]약탈 시 [ICON_RESEARCH] 과학 200 획득'
WHERE Tag = 'TXT_KEY_PROMOTION_MOON_STRIKER_HELP';

-- Near Capital Bonus
UPDATE Language_ko_KR
SET Text = '[ICON_CAPITAL]수도에서 전투 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR][NEWLINE][COLOR:110:110:110:255](멀어질수록 전투력 감소)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP';

-- Lightning Warfare
UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR][NEWLINE][COLOR_POSITIVE_TEXT]ZOC[ENDCOLOR] 무시[NEWLINE][ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_HELP';

-- Patriotic War
UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]도시[ENDCOLOR] 안 또는 옆에서 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+20%[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_NATIONALISM_HELP';

-- Penalty Attacking Cities (25)
UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_NEGATIVE_TEXT]-25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY_HELP';

-- Penalty Attacking Cities (33)
UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_NEGATIVE_TEXT]-33%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY_HELP';

UPDATE Language_ko_KR
SET Text = '지형에 상관없이 타일마다 [ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]1[ENDCOLOR] 소모'
WHERE Tag = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST';

-- Bonus vs Mounted (50)
UPDATE Language_ko_KR
SET Text = '기마 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP';

-- Enhanced Medic
UPDATE Language_ko_KR
SET Text = '이 타일과 인접 타일에 있는 아군 유닛은 매 턴 [COLOR_POSITIVE_TEXT]HP를 +10 회복[ENDCOLOR]합니다.[NEWLINE]인접한 적 유닛은 매 턴마다 10의 피해를 입습니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP';

-- Trade Mission Bonus
UPDATE Language_ko_KR
SET Text = '외교 임무에서 [ICON_GOLD] 골드 +100%'
WHERE Tag = 'TXT_KEY_PROMOTION_TRADE_MISSION_BONUS_HELP';

UPDATE Language_ko_KR
SET Text = '에이스 파일럿 IV'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE';

UPDATE Language_ko_KR
SET Text = '적 공중 유닛 요격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+34%[ENDCOLOR][NEWLINE]작전 반경 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR][NEWLINE]추가 요격 기회 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE_HELP';

-- March
UPDATE Language_ko_KR
SET Text = '행동 여부에 상관없이 매 턴 체력 회복'
WHERE Tag = 'TXT_KEY_PROMOTION_MARCH_HELP';

-- Drill
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]도시로부터 받는 피해 [COLOR_POSITIVE_TEXT]-15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]도시로부터 받는 피해 [COLOR_POSITIVE_TEXT]-15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]도시로부터 받는 피해 [COLOR_POSITIVE_TEXT]-15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_3_HELP';

-- Shock
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]측면 공격 보너스 [COLOR_POSITIVE_TEXT]+5%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]측면 공격 보너스 [COLOR_POSITIVE_TEXT]+5%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]측면 공격 보너스 [COLOR_POSITIVE_TEXT]+5%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_3_HELP';

-- Accuracy
UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 이하[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 이하[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 이하[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_3_HELP';

-- Barrage
UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 초과[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 초과[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 초과[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_3_HELP';

-- Woodsman
UPDATE Language_ko_KR
SET Text = '험지에서 방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]숲 및 정글 타일에서 [ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]두 배[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODSMAN_HELP';

-- Formation
UPDATE Language_ko_KR
SET Text = '기마 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]평지에서 방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_1_HELP';

UPDATE Language_ko_KR
SET Text = '기마 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]평지에서 방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_2_HELP';

UPDATE Language_ko_KR
SET Text = '돌격 I'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE';

UPDATE Language_ko_KR
SET Text = '평지에서 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]부상 유닛 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+20%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE_HELP';

-- Ambush
UPDATE Language_ko_KR
SET Text = '기갑 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]험지에서 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR][NEWLINE][NEWLINE][COLOR_CYAN]연소[ENDCOLOR] 연구 필요'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_1_HELP';

UPDATE Language_ko_KR
SET Text = '기갑 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]험지에서 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR][NEWLINE][NEWLINE][COLOR_CYAN]연소[ENDCOLOR] 연구 필요'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_2_HELP';

UPDATE Language_ko_KR
SET Text = '평지 보너스(30)'
WHERE Tag = 'TXT_KEY_PROMOTION_OPEN_TERRAIN';

-- Morale 
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MORALE_HELP';

UPDATE Language_ko_KR
SET Text = '대전차 구역'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_TANK';

-- Cover
UPDATE Language_ko_KR
SET Text = '원거리 공격 방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_1_HELP';

UPDATE Language_ko_KR
SET Text = '원거리 공격 방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_2_HELP';

UPDATE Language_ko_KR
SET Text = '통일'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]인접한 아군 유닛마다 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE_HELP';

-- Targeting
UPDATE Language_ko_KR
SET Text = '해상 및 지상 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 이하[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_1_HELP';

UPDATE Language_ko_KR
SET Text = '해상 및 지상 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 이하[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_2_HELP';

UPDATE Language_ko_KR
SET Text = '해상 및 지상 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]50% 이하[ENDCOLOR] 유닛 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_3_HELP';

-- Bombardment
UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]도시 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]도시 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]도시 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP';

-- Boarding Party
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR][NEWLINE]근접 전투 시 적 유닛에 [COLOR_PLAYER_PURPLE]승선 I[ENDCOLOR] [COLOR:110:110:110:255](적 [ICON_MOVES]이동력 -2)[ENDCOLOR] 상태를 부여'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR][NEWLINE]근접 해상 유닛이 부여하는 [COLOR_PLAYER_PURPLE]승선 I - II[ENDCOLOR] 효과에 면역'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR][NEWLINE]근접 전투 시 적 유닛에 [COLOR_PLAYER_PURPLE]승선 II[ENDCOLOR] [COLOR:110:110:110:255](적 [ICON_MOVES]이동력 -4)[ENDCOLOR] 상태를 부여'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP';

UPDATE Language_ko_KR
SET Text = '선체 I'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]+10[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP';

UPDATE Language_ko_KR
SET Text = '선체 II'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]+15[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP';

UPDATE Language_ko_KR
SET Text = '선체 III'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]+15[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP';

-- Ranged Support Fire
UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]유닛[ENDCOLOR]을 공격하기 전에, 50%의 [ICON_STRENGTH]전투력으로 [COLOR_POSITIVE_TEXT]원거리 공격[ENDCOLOR]을 수행합니다.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGED_SUPPORT_FIRE_HELP';

-- Wolfpack
UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR][NEWLINE][ICON_VP_VISION] 시야 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1_HELP';

UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR][NEWLINE][ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2_HELP';

UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR][NEWLINE]가능하다면 각 턴의 첫 근접 공격을 피해 후퇴'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3_HELP';

UPDATE Language_ko_KR
SET Text = '공중 목표 설정 I'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1';

UPDATE Language_ko_KR
SET Text = '공중 목표 설정 II'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_2';

UPDATE Language_ko_KR
SET Text = '해상 및 지상 유닛 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP';

UPDATE Language_ko_KR
SET Text = '폭뢰 I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I';

UPDATE Language_ko_KR
SET Text = '폭뢰 II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II';

-- Air Ambush I, Air Ambush II
UPDATE Language_ko_KR
SET Text = '기갑 유닛 대항 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP';

-- Siege (Air)
UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP';

UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP';

UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP';

UPDATE Language_ko_KR
SET Text = '결사대'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE';

UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]-10%[ENDCOLOR][NEWLINE]도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+100%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE_HELP';

UPDATE Language_ko_KR
SET Text = '공성 기관'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE';

UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+100%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_HELP';

UPDATE Language_ko_KR
SET Text = '해골 열쇠'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT';

UPDATE Language_ko_KR
SET Text = '도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+150%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT_HELP';

-- Armor Plating
UPDATE Language_ko_KR
SET Text = '방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_1_HELP';

UPDATE Language_ko_KR
SET Text = '방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_2_HELP';

UPDATE Language_ko_KR
SET Text = '방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_3_HELP';

-- Volley
UPDATE Language_ko_KR
SET Text = '요새화한 유닛 및 도시 공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_VOLLEY_HELP';

-- Survivalism
UPDATE Language_ko_KR
SET Text = '방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR][NEWLINE]우호 영토 밖 체력 회복 시 턴마다 추가 회복 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE Language_ko_KR
SET Text = '방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR][NEWLINE]우호 영토 밖 체력 회복 시 턴마다 추가 회복 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE Language_ko_KR
SET Text = '행동 여부에 상관없이 [COLOR_POSITIVE_TEXT]매 턴 체력 회복[ENDCOLOR][NEWLINE]약탈 시 [ICON_MOVES] 이동력 소모 없음.'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

-- Amphibious
UPDATE Language_ko_KR
SET Text = '해양 또는 강 건너 공격 페널티 제거[NEWLINE]강 건너 이동 시 [ICON_MOVES] 이동력 [COLOR_POSITIVE_TEXT]1[ENDCOLOR]만 소모, 습지에서 [ICON_MOVES] 이동력 두 배'
WHERE Tag = 'TXT_KEY_PROMOTION_AMPHIBIOUS_HELP';

-- Medic
UPDATE Language_ko_KR
SET Text = '같은 타일 및 인접 타일의 아군 유닛이 체력 회복 시 턴마다 추가 회복 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_HELP';

-- Medic II
UPDATE Language_ko_KR
SET Text = '같은 타일 및 인접 타일의 아군 유닛이 체력 회복 시 턴마다 추가 회복 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR][NEWLINE]우호 영토 밖 체력 회복 시 턴마다 추가 회복 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_II_HELP';

UPDATE Language_ko_KR
SET Text = '강인'
WHERE Tag = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';

UPDATE Language_ko_KR
SET Text = '국내 집중'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO';

UPDATE Language_ko_KR
SET Text = '[COLOR_RESEARCH_STORED]나침반[ENDCOLOR] 연구 전까지 대양에서 턴을 끝낼 수 없음[NEWLINE]연안에서 턴 종료 시 대양 타일 통과 가능[NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP';

UPDATE Language_ko_KR
SET Text = '바다의 위험'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE';

UPDATE Language_ko_KR
SET Text = '제공권 I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR';

UPDATE Language_ko_KR
SET Text = '제공권 II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR_II';

-- Logistics
UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_NEGATIVE_TEXT]-30%[ENDCOLOR][NEWLINE][COLOR_POSITIVE_TEXT]두 번[ENDCOLOR] 공격 가능'
WHERE Tag = 'TXT_KEY_PROMOTION_LOGISTICS_HELP';

-- Blitz
UPDATE Language_ko_KR
SET Text = '턴마다 [COLOR_POSITIVE_TEXT]두 번[ENDCOLOR] 공격 할 수 있고, 공격 후 이동이 가능'
WHERE Tag = 'TXT_KEY_PROMOTION_BLITZ_HELP';

-- Indirect Fire
UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_NEGATIVE_TEXT]-10%[ENDCOLOR][NEWLINE]장애물 넘어 [ICON_RANGE_STRENGTH]원거리 공격 가능 [COLOR:110:110:110:255](시야 확보 시)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP';

-- Range
UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_RANGE_STRENGTH]원거리 전투력 [COLOR_NEGATIVE_TEXT]-20%[ENDCOLOR][NEWLINE]사거리 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGE_HELP';

-- Heavy Charge
UPDATE Language_ko_KR
SET Text = '후퇴할 수 없는 적 상대로 [ICON_STRENGTH] 전투력이 50% 증가합니다. 적이 이 유닛보다 최종 [ICON_STRENGTH] 전투력이 낮다면 강제로 후퇴합니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_HEAVY_CHARGE_HELP';

-- Naval Movement
UPDATE Language_ko_KR
SET Text = '[ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_MOVEMENT_HELP';

-- Supply
UPDATE Language_ko_KR
SET Text = '우호 영토 밖 체력 회복 가능[NEWLINE]우호 영토 밖 체력 회복 시 턴마다 추가 회복 [COLOR_POSITIVE_TEXT]+5[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SUPPLY_HELP';

UPDATE Language_ko_KR
SET Text = '전차 헌터 I'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_1';

UPDATE Language_ko_KR
SET Text = '전차 헌터 II'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_2';

UPDATE Language_ko_KR
SET Text = '헬리콥터 대항 보너스 (150)'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';

UPDATE Language_ko_KR
SET Text = '회피'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]공습[ENDCOLOR] 작전 중 받는 피해 -50%'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_HELP';

UPDATE Language_ko_KR
SET Text = '공중 침투 I'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_I';

UPDATE Language_ko_KR
SET Text = '공중 침투 II'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_II';

-- Golden Age from Victories
UPDATE Language_ko_KR
SET Text = '적 유닛 처치 시 [ICON_STRENGTH] 전투력의 100%만큼 [ICON_GOLDEN_AGE]황금기 점수 제공'
WHERE Tag = 'TXT_KEY_PROMOTION_GOLDEN_AGE_POINTS_HELP';

-- Naval Leadership
UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]함대 수리[ENDCOLOR] 사용 가능[NEWLINE]주변 해상 유닛의 전투력 증가[NEWLINE][ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP';

-- Exploration
UPDATE Language_ko_KR
SET Text = '[ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP';

-- Haka War Dance
UPDATE Language_ko_KR
SET Text = '인접한 적 유닛의 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]-15%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_HAKA_WAR_DANCE_HELP';

-- Buffalo Chest
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]체력 [COLOR_POSITIVE_TEXT]+25[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_CHEST_HELP';

-- Buffalo Horns
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE]측면 공격 보너스 [COLOR_POSITIVE_TEXT]+25%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_HORNS_HELP';

-- Buffalo Loins
UPDATE Language_ko_KR
SET Text = '[ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+10%[ENDCOLOR][NEWLINE][ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_LOINS_HELP';

UPDATE Language_ko_KR
SET Text = '빠른 치유'
WHERE Tag = 'TXT_KEY_PROMOTION_FASTER_HEAL';

UPDATE Language_ko_KR
SET Text = '요격 I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_I';

UPDATE Language_ko_KR
SET Text = '요격 II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_II';

UPDATE Language_ko_KR
SET Text = '요격 III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_III';

UPDATE Language_ko_KR
SET Text = '요격 IV'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_IV';

UPDATE Language_ko_KR
SET Text = '에이스 파일럿 I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1';

UPDATE Language_ko_KR
SET Text = '적 공중 유닛 요격 확률 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1_HELP';

UPDATE Language_ko_KR
SET Text = '에이스 파일럿 II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2';

UPDATE Language_ko_KR
SET Text = '적 공중 유닛 요격 확률 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]적 공중 유닛 요격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2_HELP';

UPDATE Language_ko_KR
SET Text = '에이스 파일럿 III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3';

UPDATE Language_ko_KR
SET Text = '적 공중 유닛 요격 확률 [COLOR_POSITIVE_TEXT]+34%[ENDCOLOR][NEWLINE]적 공중 유닛 요격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]작전 반경 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3_HELP';

-- Air Sweep
UPDATE Language_ko_KR
SET Text = '요격 유닛을 격추하여 대공 무력화 수행 가능'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SWEEP_HELP';

-- Dogfighting
UPDATE Language_ko_KR
SET Text = '대공 무력화 수행 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]대공 무력화로 요격 불가 시 목표 유닛에 인접한 모든 적 공중 유닛에 피해 [COLOR_POSITIVE_TEXT]5[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP';

UPDATE Language_ko_KR
SET Text = '대공 무력화 수행 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR][NEWLINE]대공 무력화로 요격 불가 시 목표 유닛에 인접한 모든 적 공중 유닛에 피해 [COLOR_POSITIVE_TEXT]10[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP';

UPDATE Language_ko_KR
SET Text = '대공 무력화 수행 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+34%[ENDCOLOR][NEWLINE]대공 무력화로 요격 불가 시 목표 유닛에 인접한 모든 적 공중 유닛에 피해 [COLOR_POSITIVE_TEXT]15[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP';

-- Embarkation with Defense
UPDATE Language_ko_KR
SET Text = '승선 시 [ICON_STRENGTH] 전투력 +100%'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP';

-- Embarkation with Ocean Movement
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]연안[ENDCOLOR] 타일로 승선할 수 있음[NEWLINE]승선 시 [COLOR_POSITIVE_TEXT]대양[ENDCOLOR] 타일로 이동 가능, [ICON_VP_VISION] 시야 +1'
WHERE Tag = 'TXT_KEY_PROMOTION_ALLWATER_EMBARKATION_HELP';

-- Sapper
UPDATE Language_ko_KR
SET Text = '적 도시에 인접 시 2타일 이내에 있는 다른 아군 유닛의 도시 공격 [ICON_STRENGTH]보너스 [COLOR_POSITIVE_TEXT]+40%[ENDCOLOR][NEWLINE]적 도시에 2타일 이내에 인접 시 2타일 이내에 있는 다른 아군 유닛의 도시 공격 [ICON_STRENGTH]보너스 [COLOR_POSITIVE_TEXT]+20%[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]보너스 중첩 불가[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SAPPER_HELP';

-- Exotic Cargo
UPDATE Language_ko_KR
SET Text = '도시 국가와 인접한 영토에서 이국적인 상품 판매 가능[NEWLINE]판매 시 [ICON_CAPITAL]수도까지의 거리에 비례하여 [ICON_GOLD]골드 및 경험치 획득[NEWLINE]두 번 판매할 수 있음[NEWLINE][NEWLINE]이국적인 화물 판매 시 [COLOR_POSITIVE_TEXT]페이토이라[ENDCOLOR]가 해당 영토에 자동으로 건설 [COLOR:105:105:105:255](가능한 경우)[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SELL_EXOTIC_GOODS_HELP';

-- Mystic Blade
UPDATE Language_ko_KR
SET Text = Text || '[NEWLINE][NEWLINE][ICON_BULLET][COLOR:30:200:255:255]{TXT_KEY_PROMOTION_INVULNERABIILITY}[ENDCOLOR]: 모든 피해 2 감소. 회복 시 체력 20 추가 회복[NEWLINE][ICON_BULLET][COLOR:30:200:255:255]{TXT_KEY_PROMOTION_SNEAK_ATTACK}[ENDCOLOR]: [COLOR_POSITIVE_TEXT]측면 공격[ENDCOLOR] +20%. [COLOR_POSITIVE_TEXT]지형 이동 비용[ENDCOLOR] 및 [COLOR_POSITIVE_TEXT]ZOC[ENDCOLOR] 무시.[NEWLINE][ICON_BULLET][COLOR:30:200:255:255]{TXT_KEY_PROMOTION_AMBITION}[ENDCOLOR]: 공격 시 [ICON_STRENGTH] 전투력 보너스 +30%. 방어 시[ICON_STRENGTH] 전투력 보너스 +5%.[NEWLINE][ICON_BULLET][COLOR:30:200:255:255]{TXT_KEY_PROMOTION_RESTLESSNESS}[ENDCOLOR]: [COLOR_POSITIVE_TEXT]두 번[ENDCOLOR] 공격 가능. [ICON_MOVES] 이동력 +1.[NEWLINE][ICON_BULLET][COLOR:30:200:255:255]{TXT_KEY_PROMOTION_ENEMY_BLADE}[ENDCOLOR]: [COLOR_POSITIVE_TEXT]적 영토[ENDCOLOR]에서 턴 시작 시 체력 +10 회복. [COLOR_POSITIVE_TEXT]매 턴[ENDCOLOR] 인접한 적 유닛에게 피해 10[NEWLINE][ICON_BULLET][COLOR:30:200:255:255]{TXT_KEY_PROMOTION_EVIL_SPIRITS}[ENDCOLOR]: 공격 시 [ICON_STRENGTH] 전투력 보너스 +5%. 방어 시[ICON_STRENGTH] 전투력 보너스 +30%.'
WHERE Tag = 'TXT_KEY_PROMOTION_MYSTIC_BLADE_HELP';

UPDATE Language_ko_KR
SET Text = '모집'
WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE';

UPDATE Language_ko_KR
SET Text = '적 영토에서 턴을 시작할 경우 체력 회복 [COLOR_POSITIVE_TEXT]10[ENDCOLOR], 인접한 적에게 10 피해'
WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE_HELP';

UPDATE Language_ko_KR
SET Text = '조상의 보호'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS';

UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+5%[ENDCOLOR][NEWLINE]방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS_HELP';

UPDATE Language_ko_KR
SET Text = '결정'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION';

UPDATE Language_ko_KR
SET Text = '공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+30%[ENDCOLOR][NEWLINE]방어 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+5%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION_HELP';

UPDATE Language_ko_KR
SET Text = '끊임없음'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS';

UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]두 번[ENDCOLOR] 공격 가능[NEWLINE][ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS_HELP';

-- Sneak Attack
UPDATE Language_ko_KR
SET Text = '[COLOR_POSITIVE_TEXT]측면 보너스[ENDCOLOR]가 20% 증가합니다.[NEWLINE][COLOR_POSITIVE_TEXT]지형 특성[ENDCOLOR]과 [COLOR_POSITIVE_TEXT]ZOC[ENDCOLOR]를 무시합니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_SNEAK_ATTACK_HELP';

-- Invulnerability
UPDATE Language_ko_KR
SET Text = '모든 피해가 2 감소합니다.[NEWLINE]회복할 때 체력을 +20 회복합니다.'
WHERE Tag = 'TXT_KEY_PROMOTION_INVULNERABIILITY_HELP';
